version: '3.8'

services:
  web:
    build: .
    command: uvicorn srv.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/srv
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://fast_user:postgres@db:5432/fast_db
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=fast_user
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fast_db


volumes:
  postgres_data: